stages:
  data_ingestion:
    cmd: python src/mlProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/mlProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/winequality-red.csv


  data_validation:
    cmd: python src/mlProject/pipeline/stage_02_data_validation.py
    deps:
      - src/mlProject/pipeline/stage_02_data_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/winequality-red.csv
    outs:
      - artifacts/data_validation

  data_transformation:
    cmd: python src/mlProject/pipeline/stage_03_data_transformation.py
    deps:
      - src/mlProject/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation

  training:
    cmd: python src/mlProject/pipeline/stage_04_model_trainer.py
    deps:
      - src/mlProject/pipeline/stage_04_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/winequality-red.csv
    params:
      - alpha
      - l1_ratio
    outs:
      - artifacts/model_trainer/model.joblib


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_05_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/winequality-red.csv
      - artifacts/model_trainer/model.joblib
    params:
      - alpha
      - l1_ratio
    metrics:
    - scores.json:
        cache: false