# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flasksimpleapp1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://flasksimpleapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d7cbcd466834418dbedb40ea27fa998b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0865b41290c54dbbaa15edf239a76b1a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: flasksimpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d7cbcd466834418dbedb40ea27fa998b }}/mltest:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flasksimpleapp1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6ed7245f27484084bc0481175b804130 }}
        images: 'flasksimpleapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d7cbcd466834418dbedb40ea27fa998b }}/mltest:${{ github.sha }}'